### ISSUE TITLE
About showing YOLOv5 output frame in real-time with OpenCV function cv2.imshow() 

### ISSUE THREAD

**Issue by RavindraPatilg** [glenn-jocher/glenn-jocher#1]
Hello,

I want to show YOLOv5 output frame in real-time with OpenCV function cv2.imshow(). Kindly help me with same. Also, If there is any other option for it please suggest for it.

Thank you.

**Comment by glenn-jocher** [comment]
@RavindraPatilg detect.py already has an example of this, you can just use `python detect.py --view-img`. Code is here:
https://github.com/ultralytics/yolov5/blob/4bb7eb8b849fc8a90823a60e2b7a8ec9e38926bf/detect.py#L175-L176

**Comment by glenn-jocher** [comment]
Closing as off-topic for this repository.
